### ISSUE TITLE
Node Module Installation

### ISSUE THREAD

**Issue by ardakaraosmanoglu** [Sarmerer/stalker-discord-bot#1]
![image](https://user-images.githubusercontent.com/77415587/128750775-9c26f3c2-c9f9-45a6-b6d2-b4caf78dc3ed.png)

What is the problem?

**Comment by Sarmerer** [comment]
What command has thrown that?

**Comment by ardakaraosmanoglu** [comment]
I just opened the bat file. I tried to install modules like "npm i discord.js" but did not work.

**Comment by ardakaraosmanoglu** [comment]
[2021-08-10T10_33_18_239Z-debug.log](https://github.com/Sarmerer/stalker-discord-bot/files/6960885/2021-08-10T10_33_18_239Z-debug.log)

**Comment by Sarmerer** [comment]
Try to run `npm i discordjs/discord.js`

**Comment by ardakaraosmanoglu** [comment]
![image](https://user-images.githubusercontent.com/77415587/128852950-bcd4ffe3-5f17-4ea2-886b-3427049ce90f.png)

![image](https://user-images.githubusercontent.com/77415587/128853029-48b62f64-4970-49b0-a287-a9e5c2c4333b.png)

**Comment by Sarmerer** [comment]
Ok, I am going to try it myself

**Comment by Sarmerer** [comment]
I think you don't have `Git` isntalled. You can get it from [here](https://git-scm.com/downloads). `npm i` should run successfully afterwards

**Comment by ardakaraosmanoglu** [comment]
I installed it and bot is working. Thanks! 
if you added Git to Requirements it be useful :)

**Comment by Sarmerer** [comment]
Great idea, thanks, glad I could help you!
